=== obewan/d-framework/xml/dtd/page.dtd
<!ELEMENT pages (page*)>
<!ELEMENT page (title,icon?,author?,date?,image?,screen*,abstract?,comment?,progress?, formula*, text*, include?, chapter*,info*)>
<!ELEMENT chapter (title,author?,date?,image?,screen*,abstract?,comment?,progress?,(formula*|text*|include),info*)>
<!ELEMENT screen (thumb,big)>
<!ELEMENT formula (quote,cite?,comment?)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT icon (#PCDATA)>

<!ELEMENT thumb (#PCDATA)>
<!ELEMENT big (#PCDATA)>

<!ELEMENT abstract (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT progress (#PCDATA)>
<!ELEMENT include (#PCDATA)>
<!ELEMENT text (#PCDATA)>

<!ELEMENT info (#PCDATA)>
<!ELEMENT quote (#PCDATA)>
<!ELEMENT cite (#PCDATA)>

<!ATTLIST page type (article|book|website|report|software|tip) #IMPLIED>
<!ATTLIST info date CDATA #IMPLIED>
<!ATTLIST info scale (small|normal|large) #IMPLIED>
<!ATTLIST formula name CDATA #IMPLIED>

=== obewan/d-framework/xml/examples.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pages SYSTEM "./dtd/page.dtd">
<pages>
	<page>
		<title>Tabulations</title>
		<date>01/03/2017</date>
		<text><![CDATA[Δ-Framework got a template with tabulations.]]></text>
		<info>With infos</info>
		<info>and news</info>
	</page>
	<page>
		<title>Accordion</title>
		<date>01/02/2017</date>
		<text><![CDATA[Δ-Framework got a template with accordion.]]></text>
	</page>
	<page>
		<title>Magellan</title>
		<date>01/02/2017</date>
		<text><![CDATA[Δ-Framework got a template with magellan accordion.]]></text>
		<chapter>
			<title>Accordion chapter 1</title>
			<text>This is a nice text.</text>				
		</chapter>
		<chapter>
			<title>Accordion chapter 2</title>
			<text>This text is better.</text>				
		</chapter>
		<chapter>
			<title>Accordion chapter 3</title>
			<text>Amazing text.</text>				
		</chapter>
	</page>
	<page type="article">
		<title>List</title>
		<date>01/01/2017</date>
		<text><![CDATA[Δ-Framework got a template with list.]]></text>
		<text><![CDATA[List can list infos too.]]></text>
		<info scale="small">This info will be listed at first</info>
		<info scale="small">This info will be listed at second</info>
		<info scale="small">This info will be listed at third</info>
	</page>
	<page>
		<title>Modal</title>
		<icon>fi-lightbulb</icon>
		<date>01/01/2017</date>
		<text><![CDATA[Δ-Framewok got modals too.]]></text>
		
	</page>
</pages>

=== obewan/d-framework/xml/pages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pages SYSTEM "./dtd/page.dtd">
<pages>
	<page>
		<title>Home</title>
		<include>home.html</include>
		<info date="21/10/2017">
			<![CDATA[You can customize this framewok as you want and create your own components.]]>
		</info>	
		<info date="21/10/2017">
			<![CDATA[You can test the login with the user "test" and password "test". Edit the ".users.xml" hidden file in the xml directory for your needs, and edit the LoginController for more secure controls (this is just a basic login controller).]]>
		</info>	
		<info date="21/10/2017">
			<![CDATA[Start by looking at the index.php file. The ViewController is the central controller that will build the ViewLayout using a XML data sources managed by the XMLDataController. You can create and use your own DataController instead of the XMLDataController, and your own ViewControllers too.]]>				
		</info>
		<info date="21/10/2017">
			<![CDATA[This is the MVVC (ModelView View Controller) design pattern. the ModelView will fill the View pages with data collected by the Model. The Controllers are in front of the server (and the client for Ajax js controllers) and will calls the ModelViews to send back the final rendered html page. ]]>				
		</info>	
		<info date="21/10/2017">
			<![CDATA[Create and add your own PhpControllers and AjaxControllers, in the php/controller directory. 
			Edit the damsController.js in the js/controller directory for your Ajax modals.]]>
		</info>		
		<info date="21/10/2017">
			<![CDATA[Create your own View templates in the view directory and view models that will call them. ]]>
		</info>		
		<info date="21/10/2017">
			<![CDATA[Create your own Data sources in the data_model directory that extends DataMenu and DataPages, like in DataMenuXML and DataPagesXML. ]]>
		</info>
		<info date="21/10/2017">
			<![CDATA[This Î”-Framework version use Zurb-Foundation 5.5.3 as javascript UI library, but you are free to use any other library, by editing or adding new view templates in the view directory (see the layout.phtml) ]]>
		</info>
		<info date="21/10/2017">
			<![CDATA[Happy coding :)]]>
		</info>		
	</page>
	<page>
		<title>About</title>
		<icon>fi-info</icon>
		<include>about.htm</include>	
	</page>
</pages>
